---
apiVersion: v1
kind: Statefulset
metadata:
  name: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-database
  template:
    metadata:
      labels:
        app: app-database
    spec:
      containers:
      - name: db-container
        image: krishna/ipiimage:appimage
        ports:
        - containerPort: 3306
        #configmap and secret reference
        envFrom:
        - secretRef:
            name: bankapp-db-secret
      # Rsource Quota reference
      resources:
        requests:
          cpu: "100m"
          memory: 128Mi
        limits:
          cpu: "200m"
          memory: "256Mi"
          volumeMounts:
          - name: pvc-1
            mountPath: /var/lib/mysql
    volumeClaimTemplates:
    - metadata:
        name: pvc-1
      spec:
        accessModes: 
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
